"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import IsNotLogin from "./components/navbar/isNotLogin/isNotLogin";
import IsLogin from "./components/navbar/isLogin/isLogin";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//

export default function RootLayout({ children }) {
  const idUser = typeof window !== "undefined" ? localStorage.idUser : "";

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={idUser ? "hidden" : ""}>
          <IsNotLogin />
        </div>
        <div className={!idUser ? "hidden" : ""}>
          <IsLogin />
        </div>
        {children}
      </body>
    </html>
  );
}
